name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-build:
    uses: ./.github/workflows/dotnet-ci-reusable.yml
    with:
      dotnet-version: '8.0.x'
      run-tests: true